const kizNey = [
  { f: 220,  n: 'kaba rast'        },
  { f: 232,  n: 'kaba nim zirgüle' },
  { f: 235,  n: 'kaba zirgüle'     },
  { f: 244,  n: 'kaba dik zirgüle' },
  { f: 248,  n: 'kaba dügah'       },
  { f: 261,  n: 'kaba kürdi'       },
  { f: 264,  n: 'kaba dik kürdi'   },
  { f: 275,  n: 'kaba segah'       },
  { f: 279,  n: 'kaba buselik'     },
  { f: 290,  n: 'kaba dik buselik' },
  { f: 294,  n: 'kaba çargah'      },
  { f: 309,  n: 'kaba nim hicaz'   },
  { f: 313,  n: 'kaba hicaz'       },
  { f: 326,  n: 'kaba dik hicaz'   },
  { f: 330,  n: 'yegah'            },
  { f: 348,  n: 'kaba nim hisar'   },
  { f: 352,  n: 'kaba hisar'       },
  { f: 366,  n: 'kaba dik hisar'   },
  { f: 372,  n: 'hüseynî aşiran'   },
  { f: 392,  n: 'acem aşiran'      },
  { f: 397,  n: 'dik acem aşiran'  },
  { f: 412,  n: 'ırak'             },
  { f: 418,  n: 'geveşt'           },
  { f: 435,  n: 'dik geveşt'       },
  { f: 440,  n: 'rast'             },
  { f: 464,  n: 'nim zirgüle'      },
  { f: 470,  n: 'zirgüle'          },
  { f: 489,  n: 'dik zirgüle'      },
  { f: 495,  n: 'dügah'            },
  { f: 522,  n: 'kürdî'            },
  { f: 529,  n: 'dik kürdî'        },
  { f: 550,  n: 'segah'            },
  { f: 557,  n: 'buselik'          },
  { f: 559,  n: 'dik buselik'      },
  { f: 587,  n: 'çargah'           },
  { f: 619,  n: 'nim hicaz'        },
  { f: 627,  n: 'hicaz'            },
  { f: 652,  n: 'dik hicaz'        },
  { f: 660,  n: 'nevâ'             },
  { f: 696,  n: 'nim hisar'        },
  { f: 705,  n: 'hisar'            },
  { f: 733,  n: 'dik hisar'        },
  { f: 743,  n: 'hüseynî'          },
  { f: 783,  n: 'acem'             },
  { f: 794,  n: 'dik acem'         },
  { f: 825,  n: 'evç'              },
  { f: 835,  n: 'mahur'            },
  { f: 869,  n: 'dik mahur'        },
  { f: 880,  n: 'gerdaniye'        },
  { f: 927,  n: 'nim şehnaz'       },
  { f: 940,  n: 'şehnaz'           },
  { f: 978,  n: 'dik şehnaz'       },
  { f: 990,  n: 'muhayyer'         },
  { f: 1044,  n: 'sünbüle'         },
  { f: 1057,  n: 'dik sünbüle'     },
  { f: 1100, n: 'tiz segah'        },
  { f: 1114, n: 'tiz buselik'      },
  { f: 1173, n: 'tiz dik buselik'  },
  { f: 1174, n: 'tiz çargah'       },
  { f: 1238, n: 'tiz nim hicaz'    },
  { f: 1254, n: 'tiz hicaz'        },
  { f: 1304, n: 'tiz dik hicaz'    },
  { f: 1320, n: 'tiz nevâ'         },
  { f: 1380, n: 'tiz hüseynî'      }
];

const wnotes = [
  { f: 220,  n: 'g/3'           },
  { f: 232,  n: 'a/3', m: 'b'   },
  { f: 235,  n: 'a/3', m: 'bs'  },
  { f: 244,  n: 'a/3', m: 'd'   },
  { f: 248,  n: 'a/3'           },
  { f: 261,  n: 'a/3', m: '#'   },
  { f: 264,  n: 'a/3', m: '+-'  },
  { f: 275,  n: 'b/3', m: 'd'   },
  { f: 279,  n: 'b/3'           },
  { f: 290,  n: 'c/4', m: 'd'   },
  { f: 294,  n: 'c/4'           },
  { f: 309,  n: 'c/4', m: '#'   },
  { f: 313,  n: 'c/4', m: '+-'  },
  { f: 326,  n: 'c/4', m: '++-' },
  { f: 330,  n: 'd/4'           },
  { f: 348,  n: 'd/4', m: '#'   },
  { f: 352,  n: 'd/4', m: '+-'  },
  { f: 366,  n: 'd/4', m: '++-' },
  { f: 372,  n: 'e/4'           },
  { f: 392,  n: 'f/4'           },
  { f: 397,  n: 'f/4', m: '+'   },
  { f: 412,  n: 'f/4', m: '#'   },
  { f: 418,  n: 'f/4', m: '+-'  },
  { f: 435,  n: 'f/4', m: '++-' },
  { f: 440,  n: 'g/4'           },
  { f: 464,  n: 'g/4', m: '#'   },
  { f: 470,  n: 'g/4', m: '+-'  },
  { f: 489,  n: 'a/4', m: 'd'   },
  { f: 495,  n: 'a/4'           },
  { f: 522,  n: 'a/4', m: '#'   },
  { f: 529,  n: 'a/4', m: '+-'  },
  { f: 550,  n: 'b/4', m: 'd'   },
  { f: 557,  n: 'b/4'           },
  { f: 559,  n: 'c/5', m: 'd'   },
  { f: 587,  n: 'c/5'           },
  { f: 619,  n: 'c/5', m: '#'   },
  { f: 627,  n: 'c/5', m: '+-'  },
  { f: 652,  n: 'd/5', m: 'd'   },
  { f: 660,  n: 'd/5'           },
  { f: 696,  n: 'e/5', m: 'b'   },
  { f: 705,  n: 'e/5', m: 'bs'  },
  { f: 733,  n: 'e/5', m: 'd'   },
  { f: 743,  n: 'e/5'           },
  { f: 783,  n: 'f/5'           },
  { f: 794,  n: 'f/5', m: '+'   },
  { f: 825,  n: 'f/5', m: '#'   },
  { f: 835,  n: 'f/5', m: '+-'  },
  { f: 869,  n: 'g/5', m: 'd'   },
  { f: 880,  n: 'g/5'           },
  { f: 927,  n: 'g/5', m: '#'   },
  { f: 940,  n: 'a/5', m: 'bs'  },
  { f: 978,  n: 'a/5', m: 'd'   },
  { f: 990,  n: 'a/5'           },
  { f: 1044, n: 'a/5', m: '#'   },
  { f: 1057, n: 'b/5', m: 'bs'  },
  { f: 1100, n: 'b/5', m: 'd'   },
  { f: 1114, n: 'b/5'           },
  { f: 1173, n: 'c/6', m: 'd'   },
  { f: 1174, n: 'c/6'           },
  { f: 1238, n: 'c/6', m: '#'   },
  { f: 1254, n: 'c/6', m: '+-'  },
  { f: 1304, n: 'd/6', m: 'd'   },
  { f: 1320, n: 'd/6'           },
  { f: 1380, n: 'e/6'           }
];

export { kizNey, wnotes };
