const kizNey = [
  { f: 220,  n: 'kaba rast'        },
  { f: 232,  n: 'kaba nim zirgüle' },
  { f: 235,  n: 'kaba zirgüle'     },
  { f: 244,  n: 'kaba dik zirgüle' },
  { f: 248,  n: 'kaba dügah'       },
  { f: 261,  n: 'kaba kürdî'       },
  { f: 264,  n: 'kaba dik kürdî'   },
  { f: 275,  n: 'kaba segah'       },
  { f: 279,  n: 'kaba buselik'     },
  { f: 290,  n: 'kaba dik buselik' },
  { f: 294,  n: 'kaba çargah'      },
  { f: 309,  n: 'kaba nim hicaz'   },
  { f: 313,  n: 'kaba hicaz'       },
  { f: 326,  n: 'kaba dik hicaz'   },
  { f: 330,  n: 'yegah'            },
  { f: 348,  n: 'kaba nim hisar'   },
  { f: 352,  n: 'kaba hisar'       },
  { f: 366,  n: 'kaba dik hisar'   },
  { f: 372,  n: 'hüseynî aşiran'   },
  { f: 392,  n: 'acem aşiran'      },
  { f: 397,  n: 'dik acem aşiran'  },
  { f: 412,  n: 'ırak'             },
  { f: 418,  n: 'geveşt'           },
  { f: 435,  n: 'dik geveşt'       },
  { f: 440,  n: 'rast'             },
  { f: 464,  n: 'nim zirgüle'      },
  { f: 470,  n: 'zirgüle'          },
  { f: 489,  n: 'dik zirgüle'      },
  { f: 495,  n: 'dügah'            },
  { f: 522,  n: 'kürdî'            },
  { f: 529,  n: 'dik kürdî'        },
  { f: 550,  n: 'segah'            },
  { f: 557,  n: 'buselik'          },
  { f: 559,  n: 'dik buselik'      },
  { f: 587,  n: 'çargah'           },
  { f: 619,  n: 'nim hicaz'        },
  { f: 627,  n: 'hicaz'            },
  { f: 652,  n: 'dik hicaz'        },
  { f: 660,  n: 'nevâ'             },
  { f: 696,  n: 'nim hisar'        },
  { f: 705,  n: 'hisar'            },
  { f: 733,  n: 'dik hisar'        },
  { f: 743,  n: 'hüseynî'          },
  { f: 783,  n: 'acem'             },
  { f: 794,  n: 'dik acem'         },
  { f: 825,  n: 'evç'              },
  { f: 835,  n: 'mahur'            },
  { f: 869,  n: 'dik mahur'        },
  { f: 880,  n: 'gerdaniye'        },
  { f: 927,  n: 'nim şehnaz'       },
  { f: 940,  n: 'şehnaz'           },
  { f: 978,  n: 'dik şehnaz'       },
  { f: 990,  n: 'muhayyer'         },
  { f: 1044, n: 'sünbüle'          },
  { f: 1057, n: 'dik sünbüle'      },
  { f: 1100, n: 'tiz segah'        },
  { f: 1114, n: 'tiz buselik'      },
  { f: 1173, n: 'tiz dik buselik'  },
  { f: 1174, n: 'tiz çargah'       },
  { f: 1238, n: 'tiz nim hicaz'    },
  { f: 1254, n: 'tiz hicaz'        },
  { f: 1304, n: 'tiz dik hicaz'    },
  { f: 1320, n: 'tiz nevâ'         },
  { f: 1380, n: 'tiz hüseynî'      }
];

const sipurdeNey = [
  { f: 261, n: 'kaba rast' },
  { f: 275, n: 'kaba nim zirgüle' },
  { f: 279, n: 'kaba zirgüle' },
  { f: 290, n: 'kaba dik zirgüle' },
  { f: 294, n: 'kaba dügah' },
  { f: 310, n: 'kaba kürdî' },
  { f: 313, n: 'kaba dik kürdî' },
  { f: 326, n: 'kaba segah' },
  { f: 331, n: 'kaba buselik' },
  { f: 344, n: 'kaba dik buselik' },
  { f: 348, n: 'kaba çargah' },
  { f: 367, n: 'kaba nim hicaz' },
  { f: 372, n: 'kaba hicaz' },
  { f: 387, n: 'kaba dik hicaz' },
  { f: 392, n: 'yegah' },
  { f: 413, n: 'kaba nim hisar' },
  { f: 418, n: 'kaba hisar' },
  { f: 435, n: 'kaba dik hisar' },
  { f: 440, n: 'hüseynî aşiran' },
  { f: 465, n: 'acem aşiran' },
  { f: 471, n: 'dik acem aşiran' },
  { f: 489, n: 'ırak' },
  { f: 495, n: 'geveşt' },
  { f: 516, n: 'dik geveşt' },
  { f: 522, n: 'rast' },
  { f: 550, n: 'nim zirgüle' },
  { f: 557, n: 'zirgüle' },
  { f: 580, n: 'dik zirgüle' },
  { f: 587, n: 'dügah' },
  { f: 619, n: 'kürdî' },
  { f: 627, n: 'dik kürdî' },
  { f: 653, n: 'segah' },
  { f: 661, n: 'buselik' },
  { f: 687, n: 'dik buselik' },
  { f: 696, n: 'çargah' },
  { f: 734, n: 'nim hicaz' },
  { f: 743, n: 'hicaz' },
  { f: 773, n: 'dik hicaz' },
  { f: 783, n: 'nevâ' },
  { f: 826, n: 'nim hisar' },
  { f: 836, n: 'hisar' },
  { f: 870, n: 'dik hisar' },
  { f: 880, n: 'hüseynî' },
  { f: 929, n: 'acem' },
  { f: 942, n: 'dik acem' },
  { f: 979, n: 'evç' },
  { f: 991, n: 'mahur' },
  { f: 1031, n: 'dik mahur' },
  { f: 1044, n: 'gerdaniye' },
  { f: 1100, n: 'nim şehnaz' },
  { f: 1115, n: 'şehnaz' },
  { f: 1160, n: 'dik şehnaz' },
  { f: 1174, n: 'muhayyer' },
  { f: 1239, n: 'sünbüle' },
  { f: 1254, n: 'dik sünbüle' },
  { f: 1305, n: 'tiz segah' },
  { f: 1322, n: 'tiz buselik' },
  { f: 1374, n: 'tiz dik buselik' },
  { f: 1392, n: 'tiz çargah' },
  { f: 1468, n: 'tiz nim hicaz' },
  { f: 1486, n: 'tiz hicaz' },
  { f: 1547, n: 'tiz dik hicaz' },
  { f: 1566, n: 'tiz nevâ' },
  { f: 1606, n: 'tiz hüseynî' }
];

const wnotes = [
  { f: 'kaba rast',         n: 'g/3'           },
  { f: 'kaba nim zirgüle',  n: 'a/3', m: 'b'   },
  { f: 'kaba zirgüle',      n: 'a/3', m: 'bs'  },
  { f: 'kaba dik zirgüle',  n: 'a/3', m: 'd'   },
  { f: 'kaba dügah',        n: 'a/3'           },
  { f: 'kaba kürdî',        n: 'a/3', m: '#'   },
  { f: 'kaba dik kürdî',    n: 'a/3', m: '+-'  },
  { f: 'kaba segah',        n: 'b/3', m: 'd'   },
  { f: 'kaba buselik',      n: 'b/3'           },
  { f: 'kaba dik buselik',  n: 'c/4', m: 'd'   },
  { f: 'kaba çargah',       n: 'c/4'           },
  { f: 'kaba nim hicaz',    n: 'c/4', m: '#'   },
  { f: 'kaba hicaz',        n: 'c/4', m: '+-'  },
  { f: 'kaba dik hicaz',    n: 'c/4', m: '++-' },
  { f: 'yegah',             n: 'd/4'           },
  { f: 'kaba nim hisar',    n: 'd/4', m: '#'   },
  { f: 'kaba hisar',        n: 'd/4', m: '+-'  },
  { f: 'kaba dik hisar',    n: 'd/4', m: '++-' },
  { f: 'hüseynî aşiran',    n: 'e/4'           },
  { f: 'acem aşiran',       n: 'f/4'           },
  { f: 'dik acem aşiran',   n: 'f/4', m: '+'   },
  { f: 'ırak',              n: 'f/4', m: '#'   },
  { f: 'geveşt',            n: 'f/4', m: '+-'  },
  { f: 'dik geveşt',        n: 'f/4', m: '++-' },
  { f: 'rast',              n: 'g/4'           },
  { f: 'nim zirgüle',       n: 'g/4', m: '#'   },
  { f: 'zirgüle',           n: 'g/4', m: '+-'  },
  { f: 'dik zirgüle',       n: 'a/4', m: 'd'   },
  { f: 'dügah',             n: 'a/4'           },
  { f: 'kürdî',             n: 'a/4', m: '#'   },
  { f: 'dik kürdî',         n: 'a/4', m: 'bs'  },
  { f: 'segah',             n: 'b/4', m: 'd'   },
  { f: 'buselik',           n: 'b/4'           },
  { f: 'dik buselik',       n: 'c/5', m: 'd'   },
  { f: 'çargah',            n: 'c/5'           },
  { f: 'nim hicaz',         n: 'c/5', m: '#'   },
  { f: 'hicaz',             n: 'c/5', m: '+-'  },
  { f: 'dik hicaz',         n: 'd/5', m: 'd'   },
  { f: 'nevâ',              n: 'd/5'           },
  { f: 'nim hisar',         n: 'e/5', m: 'b'   },
  { f: 'hisar',             n: 'e/5', m: 'bs'  },
  { f: 'dik hisar',         n: 'e/5', m: 'd'   },
  { f: 'hüseynî',           n: 'e/5'           },
  { f: 'acem',              n: 'f/5'           },
  { f: 'dik acem',          n: 'f/5', m: '+'   },
  { f: 'evç',               n: 'f/5', m: '#'   },
  { f: 'mahur',             n: 'f/5', m: '+-'  },
  { f: 'dik mahur',         n: 'g/5', m: 'd'   },
  { f: 'gerdaniye',         n: 'g/5'           },
  { f: 'nim şehnaz',        n: 'g/5', m: '#'   },
  { f: 'şehnaz',            n: 'a/5', m: 'bs'  },
  { f: 'dik şehnaz',        n: 'a/5', m: 'd'   },
  { f: 'muhayyer',          n: 'a/5'           },
  { f: 'sünbüle',           n: 'a/5', m: '#'   },
  { f: 'dik sünbüle',       n: 'b/5', m: 'bs'  },
  { f: 'tiz segah',         n: 'b/5', m: 'd'   },
  { f: 'tiz buselik',       n: 'b/5'           },
  { f: 'tiz dik buselik',   n: 'c/6', m: 'd'   },
  { f: 'tiz çargah',        n: 'c/6'           },
  { f: 'tiz nim hicaz',     n: 'c/6', m: '#'   },
  { f: 'tiz hicaz',         n: 'c/6', m: '+-'  },
  { f: 'tiz dik hicaz',     n: 'd/6', m: 'd'   },
  { f: 'tiz nevâ',          n: 'd/6'           },
  { f: 'tiz hüseynî',       n: 'e/6'           }
];

export { kizNey, sipurdeNey, wnotes };
